import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const IMAGE_URL = 'https://www.apple.com/105/media/us/airpods-pro/2019/1299e2f5_9206_4470_b28e_08307a42f19b/anim/sequence/large/01-hero-lightpass/'
  const frameCount = 147

  const currentFrame = (index: number) => `${IMAGE_URL}${(index + 1).toString().padStart(4, '0')}.jpg`;

  const preloadImages = () => {
    for (let i = 0; i < frameCount; i++) {
      const img = new Image()
      img.src = currentFrame(i)
    }
  }

  const initialFrameSetup = (img: HTMLImageElement, ctx: CanvasRenderingContext2D) => {
    img.src = currentFrame(0)
    img.onload = () => {
      ctx.drawImage(img, 0, 0)
    }
  }

  const updateImage = (index: number, img: HTMLImageElement, ctx: CanvasRenderingContext2D) => {
    img.src = currentFrame(index)
    ctx.drawImage(img, 0, 0)
  }

  const onScroll = (img: HTMLImageElement, ctx: CanvasRenderingContext2D) => {
    const html = document.documentElement
    window.addEventListener('scroll', () => {
      const scrollTop = html.scrollTop
      const maxScrollTop = html.scrollHeight - window.innerHeight
      const scrollFraction = scrollTop / maxScrollTop
      const frameIndex = Math.min(
        frameCount - 1,
        Math.ceil(scrollFraction * frameCount)
      )
      requestAnimationFrame(() => updateImage(frameIndex, img, ctx))
    })
  }

  useEffect(() => {
      const canvas = document.getElementById("hero-lightpass") as HTMLCanvasElement
      const ctx = canvas.getContext("2d")
      const img = new Image()
      initialFrameSetup(img, ctx!)
      preloadImages()
      onScroll(img, ctx!)
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <canvas id="hero-lightpass" width={1158} height={770} />
    </div>
  )
}

export default Home
